services:
  huginn:
    image: "mjysci/huginn:arm32v7"
    container_name: ${CONTAINER_NAME:-huginn}
    restart: "unless-stopped"
    ports:
      - "3005:3000/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/huginn:/var/lib/mysql"
