services:
  tiddlywiki:
    image: "nicolaw/tiddlywiki:latest"
    container_name: ${CONTAINER_NAME:-tiddlywiki}
    restart: "unless-stopped"
    ports:
      - "8080:8080/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/TiddlyWiki:/var/lib/tiddlywiki"
