services:
  rclone:
    image: "mediadepot/rclone:latest"
    container_name: ${CONTAINER_NAME:-rclone}
    restart: "unless-stopped"
    volumes:
      - "/opt/mediadepot/apps/rclone:/srv/rclone/config"
      - "/opt/mediadepot/apps:/mnt/data"
