services:
  webgrabplus:
    image: "linuxserver/webgrabplus:latest"
    container_name: ${CONTAINER_NAME:-webgrabplus}
    restart: "unless-stopped"
    ports:
      - "80:80/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "TZ=${TZ:-Etc/UTC}"
    volumes:
      - "/srv/lsio/webgrabplus/config:/config"
      - "/srv/lsio/webgrabplus/data:/data"
