services:
  uptime-kuma:
    image: "louislam/uptime-kuma:latest"
    container_name: ${CONTAINER_NAME:-uptime-kuma}
    restart: "unless-stopped"
    ports:
      - "3001:3001/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/uptime-kuma:/app/data"
