services:
  eden:
    image: "linuxserver/eden:latest"
    container_name: ${CONTAINER_NAME:-eden}
    restart: "unless-stopped"
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "TZ=${TZ:-Etc/UTC}"
    volumes:
      - "/srv/lsio/eden/config:/config"
