services:
  drupal:
    image: "drupal:latest"
    container_name: ${CONTAINER_NAME:-drupal}
    restart: "unless-stopped"
    ports:
      - "80/tcp"
    volumes:
      - "var-www-html:/var/www/html"

volumes:
  var-www-html:
