services:
  doplarr:
    image: "linuxserver/doplarr:latest"
    container_name: ${CONTAINER_NAME:-doplarr}
    restart: "unless-stopped"
    ports:
      - "80:80/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "TZ=${TZ:-Etc/UTC}"
      - "DISCORD__TOKEN=${DISCORD__TOKEN:-change-me}"
      - "OVERSEERR__API=${OVERSEERR__API:-}"
      - "OVERSEERR__URL=${OVERSEERR__URL:-http://localhost:5055}"
      - "RADARR__API=${RADARR__API:-}"
      - "RADARR__URL=${RADARR__URL:-http://localhost:7878}"
      - "SONARR__API=${SONARR__API:-}"
      - "SONARR__URL=${SONARR__URL:-http://localhost:8989}"
      - "DISCORD__MAX_RESULTS=${DISCORD__MAX_RESULTS:-25}"
      - "DISCORD__REQUESTED_MSG_STYLE=${DISCORD__REQUESTED_MSG_STYLE:-:plain}"
      - "SONARR__QUALITY_PROFILE=${SONARR__QUALITY_PROFILE:-}"
      - "RADARR__QUALITY_PROFILE=${RADARR__QUALITY_PROFILE:-}"
      - "SONARR__ROOTFOLDER=${SONARR__ROOTFOLDER:-}"
      - "RADARR__ROOTFOLDER=${RADARR__ROOTFOLDER:-}"
      - "SONARR__LANGUAGE_PROFILE=${SONARR__LANGUAGE_PROFILE:-}"
      - "OVERSEERR__DEFAULT_ID=${OVERSEERR__DEFAULT_ID:-}"
      - "PARTIAL_SEASONS=${PARTIAL_SEASONS:-true}"
      - "LOG_LEVEL=${LOG_LEVEL:-:info}"
      - "JAVA_OPTS=${JAVA_OPTS:-}"
    volumes:
      - "/srv/lsio/doplarr/config:/config"
