services:
  helium:
    image: "linuxserver/helium:latest"
    container_name: ${CONTAINER_NAME:-helium}
    restart: "unless-stopped"
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "TZ=${TZ:-Etc/UTC}"
      - "HELIUM_CLI=${HELIUM_CLI:-https://www.linuxserver.io/}"
    volumes:
      - "/srv/lsio/helium/config:/config"
