services:
  pairdrop:
    image: "lscr.io/linuxserver/pairdrop:latest"
    container_name: ${CONTAINER_NAME:-pairdrop}
    restart: "unless-stopped"
    ports:
      - "3000:3000/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "TZ=${TZ:-Etc/UTC}"
