services:
  blender:
    image: "linuxserver/blender:latest"
    container_name: ${CONTAINER_NAME:-blender}
    restart: "unless-stopped"
    ports:
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "TZ=${TZ:-Etc/UTC}"
    volumes:
      - "/srv/lsio/blender/config:/config"
