services:
  mstream:
    image: "linuxserver/mstream:latest"
    container_name: ${CONTAINER_NAME:-mstream}
    restart: "unless-stopped"
    ports:
      - "3000:3000/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "TZ=${TZ:-Etc/UTC}"
    volumes:
      - "/srv/lsio/mstream/config:/config"
      - "/srv/lsio/mstream/music:/music"
