services:
  wireshark:
    image: "linuxserver/wireshark:latest"
    container_name: ${CONTAINER_NAME:-wireshark}
    restart: "unless-stopped"
    ports:
      - "80:80/tcp"
      - "3000:3000/tcp"
      - "3001:3001/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "TZ=${TZ:-Etc/UTC}"
    volumes:
      - "/srv/lsio/wireshark/config:/config"
