services:
  homepage:
    image: "ghcr.io/benphelps/homepage:latest"
    container_name: ${CONTAINER_NAME:-homepage}
    restart: "unless-stopped"
    ports:
      - "3000/tcp"
    environment:
      - "PGID=${PGID:-15000}"
      - "PUID=${PUID:-15000}"
      - "TZ=${TZ:-America/Los_Angeles}"
    volumes:
      - "/opt/mediadepot/apps/homepage:/app/config"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=mydnschallenge"
