services:
  gaps:
    image: "housewrecker/gaps:latest"
    container_name: ${CONTAINER_NAME:-gaps}
    restart: "unless-stopped"
    ports:
      - "8484/tcp"
    environment:
      - "TZ=${TZ:-America/Los_Angeles}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gaps.loadbalancer.server.port=8484"
      - "traefik.http.routers.gaps.entrypoints=websecure"
      - "traefik.http.routers.gaps.tls.certresolver=mydnschallenge"
