---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DB_HOST=${DB_HOST:-bookstack_db}
      - DB_USER=${DB_USER:-bookstack}
      - DB_PASS=${DATABASE_PASSWORD:-change-me}
      - DB_DATABASE=${DB_DATABASE:-bookstackapp}
    volumes:
      - /portainer/Files/AppData/Bookstack/Data:/config
    ports:
      - ${PORT:-8080}:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-change-me}
      - TZ=${TZ:-Etc/UTC}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-bookstackapp}
      - MYSQL_USER=${MYSQL_USER:-bookstack}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-change-me}
    volumes:
      - /portainer/Files/AppData/Bookstack/DB:/config
    restart: unless-stopped
