services:
  muximux:
    image: "linuxserver/muximux:latest"
    container_name: ${CONTAINER_NAME:-muximux}
    restart: "unless-stopped"
    ports:
      - "80/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-100}"
    volumes:
      - "/portainer/Files/AppData/Config/Muximux:/config"
