services:
  urbackup:
    image: "uroni/urbackup-server:latest"
    container_name: ${CONTAINER_NAME:-urbackup}
    restart: "unless-stopped"
    ports:
      - "55415:55415/tcp"
      - "55414:55414/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
    volumes:
      - "/portainer/Files/AppData/Config/urbackup:/var/urbackup"
      - "/portainer/backups:/backup"
