services:
  gitlab-ce:
    image: "gitlab/gitlab-ce:latest"
    container_name: ${CONTAINER_NAME:-gitlab-ce}
    restart: "unless-stopped"
    ports:
      - "80/tcp"
      - "443/tcp"
      - "22/tcp"
    volumes:
      - "etc-gitlab:/etc/gitlab"
      - "var-log-gitlab:/var/log/gitlab"
      - "var-opt-gitlab:/var/opt/gitlab"

volumes:
  etc-gitlab:
  var-log-gitlab:
  var-opt-gitlab:
