services:
  gazee:
    image: "linuxserver/gazee:latest"
    container_name: ${CONTAINER_NAME:-gazee}
    restart: "unless-stopped"
    ports:
      - "4242/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
    volumes:
      - "config:/config"
      - "comics:/comics"
      - "mylar:/mylar"

volumes:
  config:
  comics:
  mylar:
