services:
  transmission-openvpn-607:
    image: "haugene/transmission-openvpn:latest"
    container_name: ${CONTAINER_NAME:-transmission-openvpn-607}
    restart: "unless-stopped"
    ports:
      - "9091:9091/tcp"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-100}"
      - "OPENVPN_PROVIDER=${OPENVPN_PROVIDER:-MULLVAD}"
      - "OPENVPN_USERNAME=${OPENVPN_USERNAME:-user}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD:-change-me}"
      - "LOCAL_NETWORK=${LOCAL_NETWORK:-192.168.0.0/24}"
    volumes:
      - "/portainer/Downloads:/data"
      - "/etc/localtime:/etc/localtime"
