services:
  mysql:
    image: "mysql/mysql-server:5.7"
    container_name: ${CONTAINER_NAME:-mysql}
    restart: "unless-stopped"
    ports:
      - "3306/tcp"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-change-me}"
      - "MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST:-%}"
    volumes:
      - "var-lib-mysql:/var/lib/mysql"

volumes:
  var-lib-mysql:
